CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR(100) PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    info VARCHAR(4000) NOT NULL DEFAULT '{}',
    blocked BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS clients (
    client_id VARCHAR(100) PRIMARY KEY,
    client_secret_hash VARCHAR(100) NOT NULL,
    aud VARCHAR(200) NOT NULL,
    info VARCHAR(4000) NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS role_scopes (
    role_id BIGINT NOT NULL REFERENCES roles(role_id),
    scope VARCHAR(200) NOT NULL,
    PRIMARY KEY (role_id, scope)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id VARCHAR(100) REFERENCES users(user_id),
    role_id BIGINT NOT NULL REFERENCES roles(role_id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS client_grants (
    client_id VARCHAR(100) REFERENCES clients(client_id),
    grant_type VARCHAR(100) NOT NULL,
    PRIMARY KEY (client_id, grant_type)
);

CREATE TABLE IF NOT EXISTS client_scopes (
    client_id VARCHAR(100) REFERENCES clients(client_id),
    scope VARCHAR(200) NOT NULL,
    PRIMARY KEY (client_id, scope)
);

CREATE TABLE IF NOT EXISTS refresh_index (
    refresh_id VARCHAR(100) PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL REFERENCES users(user_id),
    client_id VARCHAR(100) NOT NULL REFERENCES clients(client_id),
    exp BIGINT NOT NULL,
    rotated BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS refresh_scopes (
    refresh_id VARCHAR(100) REFERENCES refresh_index(refresh_id),
    scope VARCHAR(200) NOT NULL,
    PRIMARY KEY (refresh_id, scope)
);

CREATE TABLE IF NOT EXISTS revocation (
    token_type VARCHAR(10) NOT NULL CHECK (token_type IN ('access', 'refresh')),
    token_id VARCHAR(100) NOT NULL,
    exp BIGINT NOT NULL,
    PRIMARY KEY (token_type, token_id)
);
