server.port=9090
spring.application.name=payments-api

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-trailing-tokens=true
spring.jackson.mapper.allow-coercion-of-scalars=false

logging.file.name=./logs/resource-server.log

rs.issuer=${AUTH_ISSUER:mini-auth}
rs.audience=${RS_AUDIENCE:payments-api}
rs.secret=${AUTH_SECRET:demo-only-secret-at-least-32-bytes-long}
rs.skew=${CLOCK_SKEW:30}
rs.auth-url=${AUTH_URL:http://localhost:8080}
